// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vpazgurvbfwyalolxuzg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZwYXpndXJ2YmZ3eWFsb2x4dXpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxMjE2NDgsImV4cCI6MjA3MDY5NzY0OH0.wOP6P-mpX6FBxB5Z0xW2c9gaH9ZImI-MylgHlZaHzHQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});